# Generated by Django 5.2.8 on 2025-12-01 10:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('user_type', models.CharField(choices=[('BOT', 'BOT'), ('USER', 'USER'), ('CELEBRITY', 'CELEBRITY')], max_length=16)),
                ('is_approved', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('followers', models.ManyToManyField(related_name='following', to='interactionApp.siteuser')),
                ('friend_requests', models.ManyToManyField(related_name='sent_requests', to='interactionApp.siteuser')),
            ],
        ),
    ]
