# Generated by Django 5.2.8 on 2025-12-03 10:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('is_rentable', models.BooleanField(default=True)),
                ('max_rent_days', models.IntegerField(default=7)),
                ('rent_per_day', models.IntegerField(default=1)),
                ('over_charge', models.IntegerField(default=2)),
                ('price', models.IntegerField(default=25)),
                ('count', models.IntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=25, unique=True)),
                ('user_type', models.CharField(choices=[('STUDENT', 'STUDENT'), ('PROFESSOR', 'PROFESSOR'), ('VISITOR', 'VISITOR')], max_length=16)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='RentedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('promised_end_date', models.DateField()),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_by', to='interactionApp.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rented_items', to='interactionApp.siteuser')),
            ],
        ),
    ]
