# Generated by Django 5.2.8 on 2025-12-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteuser',
            name='is_account_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteuser',
            name='is_password_compromised',
            field=models.BooleanField(default=False),
        ),
    ]
