# Generated by Django 5.2.8 on 2025-12-04 10:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeOffRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_date', models.DateField()),
                ('is_approved', models.BooleanField(default=False)),
                ('approval_requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exception_requests', to='interactionApp.supervisor')),
                ('raised_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_exceptions', to='interactionApp.storeassociate')),
            ],
        ),
        migrations.DeleteModel(
            name='ExceptionRequest',
        ),
    ]
