# Generated by Django 5.2.8 on 2025-12-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionApp', '0002_timeoffrequest_delete_exceptionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeoffrequest',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='timeoffrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'PENDING'), ('APPROVED', 'APPROVED'), ('DECLINED', 'DECLINED')], default='PENDING', max_length=10),
        ),
    ]
