# Generated by Django 5.2.8 on 2025-12-04 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interactionApp', '0003_remove_timeoffrequest_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeassociate',
            old_name='has_exception',
            new_name='is_on_timeoff',
        ),
    ]
