# Generated by Django 5.2.8 on 2025-12-05 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionApp', '0004_rename_has_exception_storeassociate_is_on_timeoff'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociatePaymentAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('associate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_audits', to='interactionApp.storeassociate')),
            ],
        ),
    ]
