# Generated by Django 5.2.8 on 2025-12-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interactionApp', '0005_associatepaymentaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeassociate',
            name='is_checked_in',
            field=models.BooleanField(default=False),
        ),
    ]
